version: 0.2
phases:
  install:
    commands:
      - echo "install step"
      - npm install
  pre_build:
    commands:
      - echo "prebuild step"
  build:
    commands:
      - npm run build
  post_build:
    commands:
      - echo "done!"
artifacts:
  files:
    - "build/**/*"